Part3/Part3/Models/Department.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Part3.Models
{
    [Table("tblDepartment")]
    public class Department
    {
        public int DepartmentID { get; set; }
        public string Name { get; set; }
        public List<Employee> Employees { get; set; }
    }
}

Part3/Part3/Models/Employee.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Part3.Models
{
    [Table("tblEmployee")]
    public class Employee
    {
        public int EmployeeID{ get; set; }
        public string Name { get; set; }
        public string Gender { get; set; }
        public string City { get; set; }
        public int DepartmentID { get; set; }
    }
}

Part3/Part3/Models/EmployeeContext.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace Part3.Models
{
    public class EmployeeContext : DbContext
    {
        public DbSet<Employee> employees { get; set; }
        public DbSet<Department> Departments { get; set; }
    }
}

Part3/Part3/Controllers/DepartmentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Part3.Models;
namespace Part3.Controllers
{
    public class DepartmentController : Controller
    {
        // GET: Department
        public ActionResult Index()
        {
            EmployeeContext employeeContext = new EmployeeContext();
            List<Department> departmentList = employeeContext.Departments.ToList();
            return View(departmentList);
        }
    }
}

Part3/Part3/Controllers/EmployeeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Part3.Models;
namespace Part3.Controllers
{
    public class EmployeeController : Controller
    {
        EmployeeContext employeeContext = new EmployeeContext();
        // GET: Employee
        public ActionResult Details(int id)
        {
            
            Employee employee = employeeContext.employees.Single(emp => emp.EmployeeID == id);
            //Employee employee = new Employee();
            //employee.EmployeeID = 01;
            //employee.Name = "yugesh";
            //employee.Gender = "Male";
            //employee.City = "Kathmandu"; 
            return View(employee);
        }
        public ActionResult EmployeeList(int departmentID)
        {
            List<Employee> employeeList = employeeContext.employees.Where(emp=>emp.DepartmentID==departmentID).ToList();
            return View(employeeList);
        }
    }
}

Part3/Part3/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Part3.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public string Index()
        {
            return "This is my first MVC Application";
        }
        public string GetDetails()
        {
            return "Get details Invoked";
        }
        public string RollName(string id)
        {
            return "my roll no is " + id+" Name= "+Request.QueryString["name"];
        }
        public string RollParameter(string id, string name)
        {
            return "my name is "+name+" and my roll no is " + id;
        } 
        public ViewResult ContryList()
        {
            ViewBag.countires = new List<string>()
            {
                "Nepal",
                "China",
                "US"
            };
            return View();
        }
        public ActionResult BookList()
        {
            ViewData["books"] = new List<string>
            {
                "Maths",
                "Science",
                "English"
            };
            return View();
        }
    }
}

Part3/Part3/Views/Department/Index.cshtml
@model IEnumerable<Part3.Models.Department>
@using Part3.Models;
@{
    ViewBag.Title = "Department List";
}

<h2>Department List</h2>
<ul>
    @foreach (Department deparment in Model)
    {
        <li>
            @Html.ActionLink(deparment.Name, "EmployeeList", "Employee", new { departmentID = deparment.DepartmentID },null)
        </li>
    }
</ul>

Part3/Part3/Views/Employee/Details.cshtml
@model Part3.Models.Employee
@{
    ViewBag.Title = "Employee Details";
}
<script src="~/Scripts/bootstrap.bundle.js"></script>
<link href="~/Content/bootstrap.min.css" rel="stylesheet" />
<h2>Employee Details</h2>
<table class="table table-dark">
    <tr>
        <td>EmployeeID</td>
        <td>@Model.EmployeeID</td>
    </tr>
    <tr>
        <td>Name</td>
        <td>@Model.Name</td>
    </tr>
    <tr>
        <td>Gender</td>
        <td>@Model.Gender</td>
    </tr>
    <tr>
        <td>City</td>
        <td>@Model.City</td>
    </tr>
</table>
@Html.ActionLink("Back to List","EmployeeList",new { departmentID = Model.DepartmentID })

Part3/Part3/Views/Employee/EmployeeList.cshtml
@model IEnumerable<Part3.Models.Employee>
@using Part3.Models;
@{
    ViewBag.Title = "Employee List";
}

<h2>Employee List</h2>
<ul>
    @foreach (Employee employee in Model)
    {
        <li>
            @Html.ActionLink(employee.Name, "Details", new { id = employee.EmployeeID })
        </li>
    }
</ul>
@Html.ActionLink("Back to Deparment","Index","Department")

Part3/Part3/Views/Home/BookList.cshtml
@{
    ViewBag.Title = "Book List";
}

<h2>Book List</h2>
<ul>
    @foreach (var books in (List<string>) ViewData["books"])
    {
        <li>books</li>
    }
</ul>

Part3/Part3/Views/Home/ContryList.cshtml
@{
    ViewBag.Title = "Contries List";
}

<h2>Contries List</h2>
<ul>
    @foreach (var country in ViewBag.countires)
    {
        <li>@country</li>
    }
</ul>