Part11-Creating Views To insert data/Part11-Creating Views To insert data/Models/Student.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
using System.Web.UI.WebControls;
using Part11_Creating_Views_To_insert_data.Models.Interfaces;
namespace Part11_Creating_Views_To_insert_data.Models
{
    [Table("tblStudent")]
    public class Student : IStudent
    {
        public int ID { get; set; }
        public string Name { get; set; }
        [Required]
        public string Gender { get; set; }
        [Required]
        public string Address { get; set; }
        [Required]
        public DateTime ? DateOfBirth { get; set; }
    }
}

Part11-Creating Views To insert data/Part11-Creating Views To insert data/Controllers/StudentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Part11_Creating_Views_To_insert_data.Models;
using Part11_Creating_Views_To_insert_data.Models.Interfaces;

namespace Part11_Creating_Views_To_insert_data.Controllers
{
    public class StudentController : Controller
    {
        EmployeeContext db = new EmployeeContext();
        // GET: Student
        public ActionResult Index()
        {
            List<Student> studentList = db.Students.ToList();
            return View(studentList);
        }

        [HttpGet]
        [ActionName("Create")]
        public ActionResult Create_Get()
        {
            return View();
        }

        //[HttpPost]
        //public ActionResult Create(FormCollection frmCollection)
        //{
        //    Student student = new Student();
        //    student.Name = frmCollection["Name"];
        //    student.Gender = frmCollection["Gender"];
        //    student.Address = frmCollection["Address"];
        //    student.DateOfBirth = Convert.ToDateTime(frmCollection["DateOfBirth"]);
        //    db.students.Add(student);
        //    db.SaveChanges();
        //    return Redirect("Index");
        //}

        //Using parameter insted of form collection object
        //[HttpPost]
        //public ActionResult Create(string name,string gender,string address,DateTime dateOfBirth)
        //{
        //    Student student = new Student();
        //    student.Name = name;
        //    student.Gender = gender;
        //    student.Address = address;
        //    student.DateOfBirth = Convert.ToDateTime(dateOfBirth);
        //    db.students.Add(student);
        //    db.SaveChanges();
        //    return Redirect("Index");
        //}


        //We can also take object as a parameter
        //[HttpPost]
        //public ActionResult create(Student student)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.students.Add(student);
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }
        //    return View();
        //}

        /* save operation can be done without passing any parameters using modelupdate object and eleminate method overloading using 
         * renaming the method name and using action name attribute */
        [HttpPost]
        [ActionName("Create")]
        public ActionResult Create_Post()
        {
            Student student = new Student();
            UpdateModel(student);
            if (ModelState.IsValid)
            {
                db.Students.Add(student);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View();
        }
        [HttpGet]
        [ActionName("Edit")]
        public ActionResult Edit_Get(int id)
        {
            Student student = db.Students.Single(stu => stu.ID == id);
            return View(student);
        }

        //edit post using mode as  parameter this may caus unintended update
        //[HttpPost]
        //public ActionResult Edit(Student studentUpdate)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        Student student = db.students.Single(stu => stu.ID == studentUpdate.ID);
        //        student.Name = studentUpdate.Name;
        //        student.Address = studentUpdate.Address;
        //        student.Gender = studentUpdate.Gender;
        //        student.DateOfBirth = studentUpdate.DateOfBirth;
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }
        //    return View(studentUpdate);
        //}

        //To avoid unintended update we explicitly the properties that we want to in model binding
        //[HttpPost]
        //[ActionName("Edit")]
        //public ActionResult Edit_Post(int id)
        //{
        //    Student student = db.students.Single(stu => stu.ID == id);
        //    //Black list model binding
        //    UpdateModel(student, null, null, new string[] { "Name" });
        //    if (ModelState.IsValid)
        //    {
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }
        //    return View();
        //}

        //Using Bind attribute we are abale to specify our include or exclude list insted of using 
        //string arry in update model function
        [HttpPost]
        [ActionName("Edit")]
        //public ActionResult Edit_Post([Bind(Include = "ID,Gender,Address,DateOfBirth")] Student studentUpdate)
        //{
        //public ActionResult Edit_Post([Bind(Exclude = "Name")] Student studentUpdate)
        //{
        //    studentUpdate.Name = db.students.Single(stu => stu.ID == studentUpdate.ID).Name;
        //    if (ModelState.IsValid)
        //    {
        //        Student student = db.students.Single(stu => stu.ID == studentUpdate.ID);
        //        student.Address = studentUpdate.Address;
        //        student.Gender = studentUpdate.Gender;
        //        student.DateOfBirth = studentUpdate.DateOfBirth;
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }
        //    return View(studentUpdate);
        //}

            //using Interfaces to include or exclude properties from model binding
        public ActionResult Edit_Post(int id)
        {
            Student student = db.Students.Single(stu => stu.ID == id);
            UpdateModel<IStudent>(student);
            if (ModelState.IsValid)
            {
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(student);
        }

        //Deleting data using GET request and its not good
        [HttpPost]
        public ActionResult Delete(int id)
        {
            Student student = db.Students.Single(stu => stu.ID == id);
            db.Students.Remove(student);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Part11-Creating Views To insert data/Part11-Creating Views To insert data/Views/Student/Create.cshtml
@model Part11_Creating_Views_To_insert_data.Models.Student

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Student</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Gender", new List<SelectListItem>{
                new SelectListItem{Text="Male",Value="Male"},
                new SelectListItem{Text="Female",Value="Female" } }, "Select Gender")
                @Html.ValidationMessageFor(model => model.DateOfBirth, "", new { @class = "text-danger" })
                @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateOfBirth, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateOfBirth, new { htmlAttributes = new { @class = "form-control" } })

            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

Part11-Creating Views To insert data/Part11-Creating Views To insert data/Views/Student/Edit.cshtml
@model Part11_Creating_Views_To_insert_data.Models.Student

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Student</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.HiddenFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Gender", new List<SelectListItem>
           {
               new SelectListItem {Text = "Male", Value = "Male"},
               new SelectListItem{Text = "Female", Value = "Female"}
           }, "Select Gender")

            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateOfBirth, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateOfBirth, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateOfBirth, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

Part11-Creating Views To insert data/Part11-Creating Views To insert data/Views/Student/Index.cshtml
@model IEnumerable<Part11_Creating_Views_To_insert_data.Models.Student>

@{
    ViewBag.Title = "Index";
}
<script src="~/Scripts/jquery-3.3.1.js"></script>
<script src="~/Scripts/popper.js"></script>
<script src="~/Scripts/bootstrap.js"></script>
<script src="~/Scripts/bootstrap-confirmation.min.js"></script>

<script type="text/javascript">
    $('[data-toggle=confirmation]').confirmation({
        rootSelector: '[data-toggle=confirmation]',
        // other options
    });
</script>
<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Gender)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Address)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DateOfBirth)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        using (Html.BeginForm("Delete", "Student", new { id = item.ID }))
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Gender)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Address)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DateOfBirth)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
                    @Html.ActionLink("Details", "Details", new { id = item.ID }) |

                    <button class="btn btn-default" data-toggle="confirmation">Confirmation</button>

                </td>
            </tr>
        }
    }
</table>